# Generated by Django 3.2.8 on 2021-10-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='repository',
        ),
    ]
